# Generated by Django 5.2.4 on 2025-10-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('token_fcm', models.CharField(blank=True, max_length=255, null=True)),
                ('anonymous_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
