# Generated by Django 5.2.4 on 2025-07-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CadastroUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("whatsapp", models.CharField(blank=True, max_length=20, null=True)),
                ("token_fcm", models.CharField(max_length=255, unique=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
